### PR TITLE
Add fields for achievement content

### LINKED ISSUE #117: Endpoint to retrieve AKF content info for journey destinations
An endpoint is needed to retrieve AKF content for milestones. 
The milestones/destination data and the AKF content for each destination along the journey will be seeded in a table.
For the first challenge, the milestone destinations and the steps needed to reach the destination are listed in https://docs.google.com/spreadsheets/d/1L7Ku3pPcMiP86G26na9n-QBHYZiR1ZItMCaSBxOL2R0/edit#gid=455177926.

At each of these milestone destinations, we will show AKF's activities related content.
Each destination's content has the following attributes:
    i) Title
   ii) subtitle
  iii) A block of text (can have one or more HTML formatted paragraphs. HTML tags supported should include Anchor tag (link)
  iv) one or more media items (photos and/or videos). Each media item should have a media_type and a URL.

The content for the first challenge is available in this Doc: https://drive.google.com/file/d/0B6iMyihknKS_eWs2cGNCVXQwTWY3Ny01a1U3YXVPSHNnQmRn/

Images are currently included in the doc and need to be saved in a folder to serve its URL.

### PR DESCRIPTION
**Pull request by alykhank**
Resolves #117.

### CODE REVIEW

**Comment by alykhank** [comment]
Still need to add/update tests, but the functionality and model updates are present.

**Comment by compnerd** [comment]
LG so far, the upgrade path is slight complicated due to the atomicity, but, thats a good idea.

**Comment by compnerd** [comment]
I thin that the coveralls is having the same issue that I had with the previous change - I don't see how to hit the second case while passing the first.  If you can come up with that scenario, LGTM, otherwise, I think that we should either drop the case or make it an assertion.

**Comment by alykhank** [comment]
@compnerd Sequelize still has the potential to fail the creation for some reason (which I'm not sure how to trigger) and I would prefer to return a specific status code rather than a general 500 error so let's keep the extra error handling code even without test coverage.

**Pull request merged**
